# Generated by Django 5.2.15 on 2026-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
