# Generated by Django 5.2.15 on 2026-06-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('publication_year', models.IntegerField()),
                ('total_copies', models.IntegerField()),
                ('available_copies', models.IntegerField()),
                ('shelf_location', models.CharField(blank=True, max_length=100)),
                ('book_cover', models.ImageField(blank=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
