# Generated by Django 5.2.15 on 2026-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Science', 'Science'), ('Computer Science', 'Computer Science'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Novel', 'Novel'), ('Biography', 'Biography'), ('Self Help', 'Self Help'), ('Others', 'Others')], max_length=30),
        ),
    ]
