# Generated by Django 5.2.15 on 2026-07-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_emailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
