# Generated by Django 5.2.15 on 2026-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_city_member_pincode_member_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='member',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
