# Generated by Django 5.2.15 on 2026-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_city_alter_member_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
