# Generated by Django 5.2.15 on 2026-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff')], max_length=10, unique=True)),
                ('max_books', models.PositiveIntegerField(default=3)),
                ('loan_period', models.PositiveIntegerField(default=7)),
                ('fine_per_day', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
