# Generated by Django 5.2.15 on 2026-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_booksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('book_issue_alert', models.BooleanField(default=True)),
                ('book_return_alert', models.BooleanField(default=True)),
                ('overdue_alert', models.BooleanField(default=True)),
                ('fine_alert', models.BooleanField(default=True)),
                ('new_member_alert', models.BooleanField(default=True)),
                ('notification_sound', models.BooleanField(default=True)),
                ('show_badge_count', models.BooleanField(default=True)),
                ('show_deskgtop_notification', models.BooleanField(default=True)),
                ('new_book_alert', models.BooleanField(default=True)),
                ('notification_tone', models.CharField(default='default', max_length=100)),
            ],
        ),
    ]
