# Generated by Django 5.2.15 on 2026-07-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_email', models.BooleanField(default=True)),
                ('book_issue_email', models.BooleanField(default=True)),
                ('book_return_email', models.BooleanField(default=True)),
                ('overdue_reminder', models.BooleanField(default=True)),
            ],
        ),
    ]
