# Generated by Django 5.2.15 on 2026-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('book_issued', 'Book Issued'), ('book_returned', 'Book Returned'), ('overdue', 'Overdue'), ('low_stock', 'Low Stock'), ('due_today', 'Due Today'), ('fine', 'Fine'), ('new_member', 'New Member'), ('new_book', 'New Book'), ('general', 'General')], max_length=20),
        ),
    ]
